# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ima_name', models.CharField(max_length=33)),
                ('ima_description', models.TextField()),
                ('article_image', models.ImageField(upload_to='appgallery')),
            ],
        ),
    ]
