# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='appgallery/'),
        ),
    ]
