# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgallery', '0002_auto_20190617_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='appgallery/'),
        ),
    ]
