# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgallery', '0002_category_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['ima_name']},
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(default=2),
        ),
    ]
