# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgallery', '0003_auto_20190617_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Location',
            new_name='location',
        ),
    ]
