# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgallery', '0004_auto_20190617_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='appgallery/'),
        ),
    ]
