# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgallery', '0004_auto_20190616_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
